addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "1.0.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "5.2.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "2.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.12")
//addSbtPlugin("org.wartremover"   % "sbt-wartremover" % "1.2.1")
addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.8.3")
